GET http://localhost:8080/JavaEEWebApp/api/v1/product/26/id

###

PUT http://localhost:8080/JavaEEWebApp/api/v1/product/new
Content-Type: application/json

{
  "description": "MyREST product",
  "name": "REST product 1",
  "price": 512.00
}

###

GET http://localhost:8080/JavaEEWebApp/api/v1/product/all

###

DELETE http://localhost:8080/JavaEEWebApp/api/v1/product/26/id